### ISSUE TITLE
Shopping ads parsing issue

### ISSUE THREAD

**Issue by lmahesh5** [serp-spider/search-engine-google#46] opened 2016-12-06 14:04 UTC
@gsouf Recently parsing issue is coming in pages where shopping ads are there.
You can try out any term like "buy iphone" or "buy watches" in google, there will be a shopping tab in the top with 12 or 16 ads. But crawler is trying to parse one more (some other div could be matching this ad criteria), like ad count comes as 13 or 17 in crawler and throws error as url parameter is not there for this additional count.

**Comment by gsouf** [comment] 2016-12-07 11:30
Hi @lmahesh5 

Are you talking about the shopping ads with **images** inside as on the following screenshot:

![capture d ecran 2016-12-07 a 12 29 29](https://cloud.githubusercontent.com/assets/3215399/20966062/e18785e4-bc78-11e6-81d0-e8366a68ed0d.png)


Can you show me what version of serps packages you are using with the following command please: ``composer show serps/*``

**Comment by lmahesh5** [comment] 2016-12-07 11:41
Hi @gsouf 
Yes, i am referring about that shopping images tab only.
Version which i am using : 
serps/core                  v0.1.2 Search engine scrapper
serps/http-client-curl      v0.1.0 CURL client for SERPS
serps/http-client-phantomjs v0.1.0 PhantomJS client for SERPS
serps/search-engine-google  v0.1.0 Google Rules and client for SERPS

**Comment by gsouf** [comment] 2016-12-07 19:27
@lmahesh5  thanks, I will investigate in the few next days, stay tunned.

**Comment by gsouf** [comment] 2016-12-14 16:22
@lmahesh5 you are getting the issue while parsing adwords results, right ?

**Comment by lmahesh5** [comment] 2016-12-15 00:40
@gsouf As mentioned above, error was while parsing the shopping ads with images tab. The image which you have pasted above is the place where we are getting error.

**Comment by gsouf** [comment] 2016-12-15 21:42
@lmahesh5 I can't reproduce the issue, please can you send me the exception you are getting ?

**Comment by gsouf** [comment] 2017-04-05 08:39
Hi @lmahesh5 Are you still getting this issue?

**Comment by lmahesh5** [comment] 2017-04-05 08:54
Hi @gsouf 
I locally added try catch to skip that error, so doesnt know if it still exist, will try.

**Comment by gsouf** [comment] 2017-04-05 09:12
Closing because it seems that google changed the way these results work, we can reopen in case it happens again.

**Closed by gsouf** 2017-04-05 09:12 UTC
Labels: bug
