### ISSUE TITLE
Google Mobile search - getNaturalResults does not return results for some keywords

### ISSUE THREAD

**Issue by vinod-maximizer** [serp-spider/search-engine-google#79] opened 2017-11-07 10:00 UTC
Searched 'buy pen' for mobile and getNaturalResults did not return expected result. 

Here is the search result for the same - https://mondovo-serp.s3.amazonaws.com/2017-11-07/1-1.html

**Comment by gsouf** [comment] 2017-11-07 17:27
Hi @vinod-maximizer  is it related to #78 ?

**Comment by vinod-maximizer** [comment] 2017-11-08 06:08
@gsouf it looks like a different error because it returns empty result when getNaturalResults is called.

**Comment by gsouf** [comment] 2017-11-23 08:12
@vinod-maximizer 

Can you give further on what is expected and what you get so I can dive directly into the issue.

**Comment by vinod-maximizer** [comment] 2017-11-23 09:21
@gsouf I searched for "buy pen" with 10 results per page and 10 results are there in the output file -
 https://mondovo-serp.s3.amazonaws.com/2017-11-07/1-1.html. But when getNaturalResults function is called it returns only 1.

PS: Used Google New Zealand for searching

**Comment by gsouf** [comment] 2017-11-25 11:49
Hi @vinod-maximizer the issue is fixed in master and I'll publish it with version 0.2.2

**Closed** 2017-11-25 11:48 UTC
Labels: in progress
