### ISSUE TITLE
ClassicalCardsResult rule could not get 'rc'

### ISSUE THREAD

**Issue by yumekana** [serp-spider/search-engine-google#63] opened 2017-04-28 08:51 UTC
Hi,

When I tried master branch, the ClassicalCardsResult rule could not parse mobile serp well.
I locally add additional loop to solve that like below.
(However, I set "google.co.jp" as the host to get raw serp data.)

    public function match(GoogleDom $dom, \DOMElement $node)
    {
        if ($node->getAttribute('class') == 'mnr-c' && null !== $node->childNodes->item(0)) {
            foreach ($node->childNodes->item(0)->childNodes as $node) {
                foreach ($node->childNodes as $node) {  <=============== added
                    if ($node instanceof \DOMElement && $node->getAttribute('class') == 'rc') {
                        return self::RULE_MATCH_MATCHED;
                    }
                }
            }
        }
        return self::RULE_MATCH_NOMATCH;
    }

**Comment by gsouf** [comment] 2017-04-28 08:57
Hi @yumekana that's probably the same issue as in #56 we fixed it for non mobile result but master branch is not widely used and that's an omission.  Thanks for pointing it out

**Comment by gsouf** [comment] 2017-04-29 08:26
@yumekana the issue is fixed in master, feel free to try again

**Closed** 2017-04-29 08:25 UTC
Labels: google update

**Comment by LileStyle** [comment] 2017-05-02 11:19
hi, gsouf
I tested and works just fine thanks !
