### ISSUE TITLE
Conflict with class and trait method

### ISSUE THREAD

**Issue by lmahesh5** [serp-spider/search-engine-google#50] opened 2017-02-01 10:34 UTC
Hi @gsouf 
After integration to 0.2, by following the migration steps, I am getting the following error.
FatalErrorException in GoogleUrl.php line 123:
Serps\SearchEngine\Google\GoogleUrl has colliding constructor definitions coming from traits

Please check and revert

**Comment by gsouf** [comment] 2017-02-04 23:25
@lmahesh5 I couldn't reproduce the issue but I managed to fix it. I would need you to check again and tell me if it's fixed now.

Thanks!

**Comment by lmahesh5** [comment] 2017-02-08 05:32
Hi @gsouf 
now that Colliding Constructor error is not coming.
However, if i use UserAgent i am not getting response from query function, the page keeps processing only. If the UserAgent param is passed empty then the response comes from query function.
Some issue with User Agent parameter.

**Comment by gsouf** [comment] 2017-02-10 09:17
@lmahesh5 thanks, I will open a dedicated issue

**Closed by gsouf** 2017-02-10 09:17 UTC
Labels: bug, needs review
